<div class="page-container">
	<form class="form-horizontal" method="get" action="">			
				<div class="mb10">							
				玩家ID： 
					<input type="text" name="uid" class="input-text" style="width:200px" value="<?php echo @$uid;?>" placeholder="玩家ID"> 
			途径：
			<select class="input-text Wdate" style="width: 150px;" name="way"> 
				<option value="">全部</option>
				<?php foreach ( $ways as $w ): ?>
				<option value="<?php echo $w["Way"]; ?>" <?php if ( @$way == $w["Way"]): ?> selected <?php endif;?> > <?php echo $w["Title"]; ?></option>
				<?php endforeach; ?> 
			</select>

			<input value="<?php echo @$start_time;?>" placeholder="开始时间" class="laydate-icon" onClick="laydate({istime: true, format: 'YYYY-MM-DD hh:mm:ss'})" name="start_time"/>
			-
			<input value="<?php echo @$end_time;?>" placeholder="结束时间" class="laydate-icon" onClick="laydate({istime: true, format: 'YYYY-MM-DD hh:mm:ss'})" name="end_time"/>
			
			<input type="submit" class="btn btn-primary" value="查看" /> 
		    <a class="btn btn-primary" href="/v1/data/item_log?start_time=<?php echo date('Y-m-d 00:00:00');?>&end_time=<?php echo date('Y-m-d H:i:s');?>" class="btn">今日 </a> 
		    <a class="btn btn-primary" href="/v1/data/item_log?start_time=<?php echo date('Y-m-d 00:00:00',strtotime("-6 day"));?>&end_time=<?php echo date('Y-m-d H:i:s');?>" class="btn">七天</a> 
		    <a class="btn btn-primary" href="/v1/data/item_log?start_time=<?php echo date('Y-m-01 00:00:00');?>&end_time=<?php echo date('Y-m-d H:i:s');?>" class="btn">当月</a> 
		    <a class="btn btn-primary" href="/v1/data/item_log?start_time=<?php echo date('Y-m-d 00:00:00',strtotime("-29 day"));?>&end_time=<?php echo date('Y-m-d H:i:s');?>" class="btn">30天</a>

		</form>

		<table class="table table-border table-bordered table-bg table-hover table-sort dataTable no-footer mt-20">
			<thead>
				<tr>
					<th>日志ID</th>
					<th>玩家ID</th>
					<th>物品</th>
					<th>数量</th>
					<th>余额</th>
					<th>途径</th>
					<th>GUID</th>
					<th>时间</th>
				</tr>
			</thead>				
			<?php foreach($rows as $row){?>
				<tr>
					<td><?php echo $row['id']?></td>
					<td><?php echo $row['uid']?></td>
					<td><?php echo $row['item_name']?></td>
					<td><?php echo $row['item_num']?></td>
					<td><?php echo $row['balance']?></td>
					<td><?php echo $row['way']?></td>
					<td><?php echo $row['guid']?></td>
					<td><?php echo $row['deadline']?></td>				
				</tr>
			<?php }?>

		</table>
		<div class="pages"><?php echo $pages;?></div>
</div>
