<div class="page-container">
		<table class="table table-border table-bordered table-bg table-hover table-sort dataTable no-footer mt-20">
			<thead>
				<tr>
					<th colspan="4" style="text-align:center">玩家信息</td>
				</tr>
				<tr>
					<td class="text-r">玩家ID</td>
					<td>
						<?php echo @$uid;?>
						<a href="/v1/system/add_items?uid=<?php echo @$uid;?>" class="btn btn-primary radius">补偿&扣除物品</a>
					</td>
					<td class="text-r">昵称</td>
					<td><?php echo @$user['nickname']?></td>
				</tr>
				<tr>
					<td class="text-r">金币</td>
					<td><?php echo @$user['gold']?></td>
					<td class="text-r">钻石</td>
					<td><?php echo @$user['diamond']?></td>
				</tr>
				<tr>
					<td class="text-r">房卡</td>
					<td><?php echo @$user['score_card']?></td>
					<td class="text-r">对局数</td>
					<td><?php echo @$user['play_times']?></td>
				</tr>
				<tr>
					<td class="text-r">今日对局数</td>
					<td><?php echo @$user['today_play_times']?></td>
					<td class="text-r">7日对局数</td>
					<td><?php echo @$user['day7_play_times']?></td>
				</tr>
				<tr>
					<td class="text-r">充值金额</td>
					<td><?php echo @$user['pay_rmb']?></td>
					<td class="text-r">最近登陆时间</td>
					<td><?php echo @$user['enter_time']?></td>
				</tr>
				<tr>
					<td class="text-r">注册时间</td>
					<td><?php echo @$user['create_time']?></td>
					<td></td>
					<td></td>
				</tr>
		<?php if ( empty($share) == false): ?>
		<tr>
			<th colspan="4" style="text-align:center">推广信息</th>
		</tr>
		<tr>
			<td class="text-r">真实姓名：</td>
			<td><?php echo @$share['name']; ?></td>
			<td class="text-r">手机号：</td>
			<td><?php echo @$share['phone']; ?></td>
		</tr>
		<tr>
			<td class="text-r">邀请码：</td>
			<td><?php echo @$share['share_code']; ?></td>
			<td class="text-r">级别：</td>
			<td><?php echo @$share['rank_name']; ?></td>
		</tr>
		<tr>
			<td class="text-r">二级人数：</td>
			<td><?php echo @$share['users_lv2']; ?></td>
			<td class="text-r">三级人数：</td>
			<td><?php echo @$share['users_lv3']; ?></td>
		</tr>
		<tr>
			<td class="text-r">可用金额：</td>
			<td><?php echo number_format(@$share['balance'],1); ?></td>
			<td class="text-r">累计收益：</td>
			<td><?php echo number_format(@$share['total_rebate'],1); ?></td>
		</tr>
		<tr>
			<td class="text-r">本月收益：</td>
			<td><?php echo number_format(@$share['month_rebate'],1); ?></td>
			<td class="text-r">提现中：</td>
			<td><?php echo number_format(@$share['apply_rebate'],1); ?></td>
		</tr>
		<? endif; ?>
		<? if ( empty($agent) == false ): ?>
		<tr>
			<th colspan="4" style="text-align:center">代理信息</th>
		</tr>
		<tr>
			<td class="text-r">代理等级：</td>
			<td><?php echo @$agent['agent_level']; ?></td>
			<td class="text-r">高级代理(可以给代理发房卡)：</td>
			<?php if ( @$agent['high_agent'] ):?>
			<td>是</td>
			<?php else:?>
			<td>否</td>
			<?php endif;?>
			<td></td>
		</tr>
		<tr>
			<td class="text-r">房卡库存：</td>
			<td><?php echo @$agent['agent_card']; ?></td>
			<td class="text-r">游戏充卡总计：</td>
			<td><?php echo @$agent['total_game_card']; ?></td>
		</tr>
		<tr>
			<td class="text-r">代理充卡总计：</td>
			<td><?php echo @$agent['total_agent_card']; ?></td>
			<td></td>
			<td></td>
		</tr>
		<?php endif; ?>
		<? if ( empty($marketing) == false ): ?>
		<tr>
			<th colspan="4" style="text-align:center">代理系统V2(Marketing)</th>
		</tr>
		<tr>
			<td class="text-r">推广码：</td>
			<td><?php echo @$marketing['code']; ?></td>
			<td class="text-r">绑定时间：</td>
			<td><?php echo @$marketing['bind_time']; ?></td>
		</tr>
		<tr>
			<td class="text-r">上级：</td>
			<td><a href="javascript:void(0)" onclick="Hui_admin_tab(this)" class="maincolor" data-title="玩家信息" _href="/v1/data/user_info?uid=<?php echo @$marketing['parent_uid'];?>"><?php echo @$marketing['parent_uid'];?></a></td>
			<td class="text-r">代理等级：</td>
			<td><?php echo @$marketing['level_name']; ?></td>
		</tr>
		<tr>
			<td class="text-r">二级会员：</td>
			<td><a href="javascript:void(0)" onclick="Hui_admin_tab(this)" class="maincolor" data-title="玩家" _href="/v1/marketing/user_list?parent_uid=<?php echo @$uid;?>"><?php echo $marketing['users_lv2'];?></a></td>
			<td class="text-r">三级会员：</td>
			<td><a href="javascript:void(0)" onclick="Hui_admin_tab(this)" class="maincolor" data-title="玩家" _href="/v1/marketing/user_list?grandpa_uid=<?php echo @$uid;?>"><?php echo $marketing['users_lv3'];?></a></td>
		</tr>
		<tr>
			<td class="text-r">二级充值：</td>
			<td><?php echo number_format(@$marketing['pay_lv2'],2); ?></td>
			<td class="text-r">三级充值：</td>
			<td><?php echo number_format(@$marketing['pay_lv3'],2); ?></td>
		</tr>
		<tr>
			<td class="text-r">二级返利：</td>
			<td><?php echo number_format(@$marketing['rebate_lv2'],2); ?></td>
			<td class="text-r">三级返利：</td>
			<td><?php echo number_format(@$marketing['rebate_lv3'],2); ?></td>
		</tr>
		<tr>
			<td class="text-r">累计收益：</td>
			<td><?php echo number_format(@$marketing['rebate_lv2']+@$marketing_lv3['rebate_lv3'],2); ?></td>
			<td class="text-r">提现总额：</td>
			<td><?php echo @$marketing['balance']; ?></td>
		</tr>
		<tr>
			<td class="text-r">提现中：</td>
			<td><?php echo number_format(@$marketing['apply_rebate'],2); ?></td>
			<td class="text-r">本月收益：</td>
			<td><?php echo number_format(@$marketing['month_rebate'],2); ?></td>
		</tr>
	</thead>				
	</table>
</div>

