<div class="page-container">
<div class="pd-20">
	<div class="text-c">							
	<form class="form-horizontal" method="get" action="">			
			账号： 
			<input type="text" name="account" class="input-text" style="width: 200px;" value="<?php echo @$account?>" placeholder="账号"> 
			时间：
			<input value="<?php echo @$start_time;?>" placeholder="开始时间" class="laydate-icon" onClick="laydate({istime: true, format: 'YYYY-MM-DD hh:mm:ss'})" name="start_time"/>
			-
			<input value="<?php echo @$end_time;?>" placeholder="结束时间" class="laydate-icon" onClick="laydate({istime: true, format: 'YYYY-MM-DD hh:mm:ss'})" name="end_time"/>
			
			<input type="submit" class="btn btn-primary" value="查看" /> 
		    <a class="btn btn-primary" href="/v1/admin/operate_log?start_time=<?php echo date('Y-m-d 00:00:00');?>&end_time=<?php echo date('Y-m-d H:i:s');?>" class="btn">今日 </a> 
		    <a class="btn btn-primary" href="/v1/admin/operate_log?start_time=<?php echo date('Y-m-d 00:00:00',strtotime("-6 day"));?>&end_time=<?php echo date('Y-m-d H:i:s');?>" class="btn">七天</a> 
		    <a class="btn btn-primary" href="/v1/admin/operate_log?start_time=<?php echo date('Y-m-01 00:00:00');?>&end_time=<?php echo date('Y-m-d H:i:s');?>" class="btn">当月</a> 
		    <a class="btn btn-primary" href="/v1/admin/operate_log?start_time=<?php echo date('Y-m-d 00:00:00',strtotime("-29 day"));?>&end_time=<?php echo date('Y-m-d H:i:s');?>" class="btn">30天</a>

		    <a class="btn btn-primary" download="订单.csv" class="btn" onclick="exportToExcel(this,'csv_data')">导出</a>
	</form>
	</div>

	<div class="mt-20">
	<table class="table table-border table-bordered table-bg table-hover table-sort dataTable no-footer" id="csv_data">
		<thead>
			<tr>
				<th>序号</th>
				<th>账号</th>
				<th>页面</th>
				<th>请求</th>
				<th>时间</th>
				<th>参数 </th>
			</tr>
		</thead>

		<?php foreach($rows as $row):?>
			<tr>
				<td><?php echo $row['id']?></td>
				<td><?php echo $row['account']?></td>
				<td><?php echo $row['title']?></td>
				<td><?php echo $row['link']?></td>
				<td><?php echo $row['create_time']?></td>
				<td width="50%"><?php echo $row['data'];?></td>						
			</tr>
		<?php endforeach;?>
	</table>
	</div>
	<div class="pages"><?php echo $pages;?></div>
</div>
